# Generated by Django 5.0.1 on 2024-01-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_advertisements_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(default='', upload_to='advertisemenets/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
